language: java

sudo: true


jdk:
- oraclejdk8

before_install:
- chmod +x gradlew
- ./gradlew clean

notifications:
email:
- francoluigi95@gmail.com

on_success: never
on_failure: always


sudo: required
dist: trusty
group: stable
